spring.application.name=gespa-backend
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

server.port=${PORT:8083}
server.error.include-message=never
server.error.include-binding-errors=never

spring.jackson.time-zone=America/Santiago
spring.jpa.open-in-view=false

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
